import Head from 'next/head'
import  ReactFlowProvider from './MindMap/ReactFlowProvider'
export default function Home() {
  return (
    <div >
      <Head>
        <title>Mind Map App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <ReactFlowProvider/> 
    </div>
  )
}
